site_name: some title
site_url: ""
use_directory_urls: false
docs_dir: docs
repo_url: https://github.com/ldeluigi/minimal-example
theme:
  name: material

plugins:
  - exclude:
      glob:
        - .git/*
  - search
  - offline

markdown_extensions:
  - markdown_include.include:
      base_path: docs
      inheritHeadingDepth: true
      throwException: false
